### ISSUE TITLE
radio-broadcast might help

### ISSUE THREAD

**Issue by pelikhan** [nominetresearch/microbit-networking-book#4]
We have a new package in the makecode editor (radio-broadcast) that allows to use named messages for transmission. It hides the complexity of having to do if statement on message types.

**Comment by ciseng** [comment]
I need to play around with radio-broadcast. But I could not see how it helps with message types. It seems to be helping to send enum messages - jump, start, stop etc. 
With the new blocks, the ability to receive both strings and numbers seems to have disappeared (as we used to do in the old version through settings).

**Comment by ciseng** [comment]
Fixed the writing so that it matches the current capabilities of radio blocks.
